version: '3'

services:
    app:
        build: ./app
        container_name: app
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "80:5000"
        volumes:
            - ./database.db:/app/database/database.db

        
