version: '3'

volumes:
    db_data:

services:
    app:
        build: ./app
        container_name: app
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "80:5000"
        volumes:
            - ./app/static/:/app/static/ # Dev only
            - ./app/templates/:/app/templates/ # Dev only
            - db_data:/app/database/


        
