version: '3'

services:
    app:
        build: ./app
        container_name: app
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "80:5000"
        volumes:
            - ./app/static/:/app/static/ # Dev only
            - ./app/templates/:/app/templates/ # Dev only
            - ./app/db/db/:/app/db/db/


        
